image:
  repository: skydive/skydive
  tag: "latest"
  imagePullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2000m
    memory: 8192Mi
  requests:
    cpu: 100m
    memory: 512Mi

analyzer:
  host: skydive-analyzer:8082

# Extra environment variables to be appended to default skydive variables
extraEnvs: []
#  - name: MY_ENVIRONMENT_VAR
#    value: the_value_goes_here
