---
- name: "Installing the rpmfusion repo packages"
  dnf: name={{ item }}
       state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
- name: "Updating packages"
  shell: "dnf update -y"
