apiVersion: v1
kind: ServiceAccount
metadata:
  name: skydive-analyzer
  namespace: {{ .Release.Namespace }}
  labels:
    app: skydive-analyzer
imagePullSecrets:
  - name: sa-{{ .Release.Namespace }}
