---
- name: Deploy Skydive development machine
  hosts: dev
  become: yes
  pre_tasks:
  - selinux: state=disabled
  - shell: setenforce 0
  roles:
  - role: elasticsearch
    tags: elasticsearch
  - role: orientdb
    tags: orientdb
  - role: objectstore
    tags: objectstore
  - role: skydive_dev
    tags: skydive_dev
